# Generated by Django 4.1.4 on 2022-12-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_watched_listings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
