# Generated by Django 4.1.4 on 2023-01-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_delete_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
